version: 2
jobs:
    build:
        docker:
            - image: docker:dind
              environment:
                  TAG: 0.1
                  IMAGE_NAME: app-ci
                  PRODUCTION_SERVER_IP: $PRODUCTION_SERVER_IP
                  PRODUCTION_SERVER_PATH: $PRODUCTION_SERVER_PATH
        steps:
            - checkout
            - setup_remote_docker:
                docker_layer_caching: true

            - run:
                name: "Build and push Docker image"
                command: |
                    if [ "${CIRCLE_BRANCH}" == "master" ]; then
                        docker build -t silarhi/${IMAGE_NAME}:${TAG}.$CIRCLE_BUILD_NUM -t silarhi/${IMAGE_NAME}:latest .
                    else
                        docker build -t silarhi/${IMAGE_NAME}:${TAG}.$CIRCLE_BUILD_NUM .
                    fi
                    echo ${DOCKER_PWD} | docker login -u ${DOCKER_LOGIN} --password-stdin
                    docker push silarhi/${IMAGE_NAME}
            - run:
                name: "Deploy image"
                command: |
                    if [ "${CIRCLE_BRANCH}" == "master" ]; then
                        ssh root@${PRODUCTION_SERVER_IP} "/bin/bash ${PRODUCTION_SERVER_PATH}/deploy.sh silarhi/${IMAGE_NAME}:latest"
                    fi
