version: 2
jobs:
    build:
        docker:
            - image: docker:dind
        steps:
            - checkout
            - run:
                name: "Setup Environment Variables"
                command: |
                    echo 'export TAG="0.1.${CIRCLE_BUILD_NUM}"' >> $BASH_ENV
                    echo 'export IMAGE_NAME="app-ci"' >> $BASH_ENV

            - setup_remote_docker:
                docker_layer_caching: true

            - run:
                name: "What branch am I on now?"
                command: echo $CIRCLE_BRANCH

            -  run:
                name: "What was my custom environment variable?"
                command: echo $TAG

            -  run:
                name: "What was my custom environment variable 3?"
                command: echo $CIRCLE_BUILD_NUM

            -  run:
                name: "What was my custom environment variable 2?"
                command: echo $IMAGE_NAME

            - run:
                name: "Build and push Docker image"
                command: |
                    docker build -t silarhi/${IMAGE_NAME}:${TAG} .
                    echo ${DOCKER_PWD} | docker login -u ${DOCKER_LOGIN} --password-stdin
                    docker push silarhi/${IMAGE_NAME}:${TAG}
