version: 2
jobs:
    build:
        docker:
            - image: docker:dind
              environment:
                  TAG: 0.1
                  IMAGE_NAME: app-ci
        steps:
            - checkout
            - setup_remote_docker:
                docker_layer_caching: true

            - run:
                name: "Build and push Docker image"
                command: |
                    if [ "${CIRCLE_BRANCH}" == "master" ]; then
                        docker build -t silarhi/${IMAGE_NAME}:${TAG}.$CIRCLE_BUILD_NUM -t silarhi/${IMAGE_NAME}:latest .
                    else
                        docker build -t silarhi/${IMAGE_NAME}:${TAG}.$CIRCLE_BUILD_NUM .
                    fi
                    echo ${DOCKER_PWD} | docker login -u ${DOCKER_LOGIN} --password-stdin
                    docker push silarhi/${IMAGE_NAME}
