version: 2
jobs:
    build:
        docker:
            - image: docker:dind
              environment:
                  IMAGE_NAME: silarhi/app-ci
                  PRODUCTION_SERVER_IP: $PRODUCTION_SERVER_IP
                  PRODUCTION_SERVER_PATH: $PRODUCTION_SERVER_PATH
        steps:
            - checkout
            - setup_remote_docker:
                docker_layer_caching: true

            - run:
                name: "Build and push Docker image"
                command: |
                    IMAGE_TAG="1.0.${CIRCLE_BUILD_NUM}"
                    docker build -t ${IMAGE_NAME}:${TAG} .

                    if [ "${CIRCLE_BRANCH}" == "master" ]; then
                        docker tag $IMAGE_NAME:${TAG} $IMAGE_NAME:latest
                    fi
                    echo ${DOCKER_PWD} | docker login -u ${DOCKER_LOGIN} --password-stdin
                    docker push ${IMAGE_NAME}
            - run:
                name: "Deploy image"
                command: |
                    if [ "${CIRCLE_BRANCH}" == "master" ]; then
                        ssh root@${PRODUCTION_SERVER_IP} "/bin/bash ${PRODUCTION_SERVER_PATH}/deploy.sh ${IMAGE_NAME}:latest"
                    fi
