version: 2
jobs:
    build:
        docker:
            - image: docker:dind
              environment:
                  TAG: 0.1.$CIRCLE_BUILD_NUM
                  IMAGE_NAME: app-ci
        steps:
            - checkout
            - setup_remote_docker:
                docker_layer_caching: true

            - run:
                name: "Build and push Docker image"
                command: |
                    docker build -t silarhi/${IMAGE_NAME}:${TAG} .
                    echo ${DOCKER_PWD} | docker login -u ${DOCKER_LOGIN} --password-stdin
                    docker push silarhi/${IMAGE_NAME}:${TAG}
