version: 2
jobs:
    build:
        docker:
            - image: docker:dind
        steps:
            - checkout
            -   run:
                name: Setup VirtualEnv
                command: |
                echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
                echo 'export IMAGE_NAME=app-ci' >> $BASH_ENV
                virtualenv helloworld
                . helloworld/bin/activate
            - setup_remote_docker:
                docker_layer_caching: true
            - run:
                name: Build and push Docker image
                command: |
                    . helloworld/bin/activate
                    docker build -t silarhi/$IMAGE_NAME:$TAG .
                    echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
                    docker push silarhi/$IMAGE_NAME:$TAG
